name: Download Ahwaktv Video
on:
  workflow_dispatch:
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
      - name: Install Python deps
        run: pip install seleniumbase curl_cffi
      - name: Run script
        run: python ahwaktv_multi_server_downloader.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-video
          path: downloads/
          retention-days: 7
